In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   	Email                500 non-null    object
 1   Address               500 non-null    object
 2   Avatar                500 non-null    object
 3   Time on App           500 non-null    float64
 4   Time on Website       500 non-null    float64
 5   Length of Membership  500 non-null    float64
 6   Yearly Amount Spent   500 non-null    float64
dtypes: float64(4), object(3)
memory usage: 27.5+ KB

In [5]:
df.head()

,\tEmail,Address,Avatar,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
0,mstephenson@fernandez.com,"835 Frank TunnelWrightmouth, MI 82180-9605",Violet,12.66,39.58,4.08,587.95
1,hduke@hotmail.com,"4547 Archer CommonDiazchester, CA 06566-8576",DarkGreen,11.11,37.27,2.66,392.20
2,pallen@yahoo.com,"24645 Valerie Unions Suite 582Cobbborough, DC ...",Bisque,11.33,37.11,4.10,487.55
3,riverarebecca@gmail.com,"1414 David ThroughwayPort Jason, OH 22070-1220",SaddleBrown,13.72,36.72,3.12,581.85
4,mstephens@davidson-herman.com,"14023 Rodriguez PassagePort Jacobville, PR 372...",MediumAquaMarine,12.80,37.54,4.45,599.41

In [6]:
df.describe()

       Time on App  Time on Website  Length of Membership  Yearly Amount Spent
count   500.000000       500.000000             500.00000           500.000000
mean     12.052620        37.060480               3.53336           499.314240
std       0.994418         1.010555               0.99926            79.314764
min       8.510000        33.910000               0.27000           256.670000
25%      11.390000        36.347500               2.93000           445.037500
50%      11.980000        37.070000               3.53500           498.890000
75%      12.752500        37.720000               4.13000           549.312500
max      15.130000        40.010000               6.92000           765.520000

In [8]:
df.columns = df.columns.str.strip()

In [9]:
df.columns

Index(['Email', 'Address', 'Avatar', 'Time on App', 'Time on Website',
       'Length of Membership', 'Yearly Amount Spent'],
      dtype='object')

In [10]:
df.shape

(500, 7)

In [11]:
df.loc[df["Avatar"] == "Blue", ["Email", "Avatar"]]

                                      Email Avatar
266  christophermorrison@mcguire-carter.biz   Blue
289         jamesfaulkner@hoffman-wolfe.org   Blue
423                      dana59@hotmail.com   Blue
445                    aschmidt@johnson.biz   Blue

In [15]:
df.iloc[:5, 2:]

,Avatar,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
0,Violet,12.66,39.58,4.08,587.95
1,DarkGreen,11.11,37.27,2.66,392.20
2,Bisque,11.33,37.11,4.10,487.55
3,SaddleBrown,13.72,36.72,3.12,581.85
4,MediumAquaMarine,12.80,37.54,4.45,599.41

In [13]:
df.isna().sum()

Email                   0
Address                 0
Avatar                  0
Time on App             0
Time on Website         0
Length of Membership    0
Yearly Amount Spent     0
dtype: int64

In [16]:
df["Avatar"] = df["Avatar"].fillna("Unknown")

In [18]:
df["Yearly Amount Spent"] > df["Yearly Amount Spent"].mean()

0       True
1      False
2      False
3       True
4       True
       ...
495     True
496     True
497     True
498    False
499    False
Name: Yearly Amount Spent, Length: 500, dtype: bool

In [25]:
(df["Avatar"] == "Blue") & (df["Yearly Amount Spent"] > df["Yearly Amount Spent"].mean())[["Email", "Yearly Amount Spent"]].sort_values(by= "Yearly Amount Spent", acsending=True)

(0      False
 1      False
 2      False
 3      False
 4      False
        ...
 495    False
 496    False
 497    False
 498    False
 499    False
 Length: 500, dtype: bool,
 [['Email', 'Yearly Amount Spent']])

In [26]:
df.isna().sum()
df["Avatar"] = df["Avatar"].fillna("Unknown")

Email                   0
Address                 0
Avatar                  0
Time on App             0
Time on Website         0
Length of Membership    0
Yearly Amount Spent     0
dtype: int64

In [ ]:
df[(df["Avatar"] == "Blue") & (df["Yearly Amount Spent"] > df["Yearly Amount Spent"].mean())][["Email", "Yearly Amount Spent"]].sort_values(by="Yearly Amount Spent", ascending=False)

# Step 1 — The simplest groupby

Question:
“What is the average yearly spend per Avatar?”

In [30]:
df.groupby("Avatar")["Yearly Amount Spent"].mean().tail(10)

Avatar
Teal           458.111429
Thistle        530.784000
Tomato         473.330000
Turquoise      540.251667
Violet         430.690000
Wheat          551.271667
White          516.028000
WhiteSmoke     524.142500
Yellow         562.080000
YellowGreen    460.696667
Name: Yearly Amount Spent, dtype: float64

# Step 2 — Turn it into a DataFrame (common quiz move)

If they want a table instead of a Series:

In [29]:
df.groupby("Avatar", as_index=False)["Yearly Amount Spent"].mean().head(10)

           Avatar  Yearly Amount Spent
0       AliceBlue           473.625000
1    AntiqueWhite           465.944000
2            Aqua           502.643333
3      Aquamarine           444.800000
4           Azure           452.630000
5           Beige           483.503333
6          Bisque           484.231667
7           Black           500.870000
8  BlanchedAlmond           524.904000
9            Blue           498.922500

# Step 3 — Multiple aggregations (this is big-boy Pandas)

Question:
“Show mean and max yearly spend per Avatar.”

In [31]:
df.groupby("Avatar")["Yearly Amount Spent"].agg(["mean", "max"])

                    mean     max
Avatar
AliceBlue     473.625000  478.58
AntiqueWhite  465.944000  541.97
Aqua          502.643333  553.60
Aquamarine    444.800000  511.98
Azure         452.630000  452.63
...                  ...     ...
Wheat         551.271667  744.22
White         516.028000  593.16
WhiteSmoke    524.142500  551.02
Yellow        562.080000  562.08
YellowGreen   460.696667  533.40

[138 rows x 2 columns]

# Step 4 — Rename columns (clean output)

In [33]:
df.groupby("Avatar")["Yearly Amount Spent"].agg(
    avg_speed = "mean", 
    max_spend = "max"
)

               avg_speed  max_spend
Avatar
AliceBlue     473.625000     478.58
AntiqueWhite  465.944000     541.97
Aqua          502.643333     553.60
Aquamarine    444.800000     511.98
Azure         452.630000     452.63
...                  ...        ...
Wheat         551.271667     744.22
White         516.028000     593.16
WhiteSmoke    524.142500     551.02
Yellow        562.080000     562.08
YellowGreen   460.696667     533.40

[138 rows x 2 columns]

# Step 5 — value_counts() (frequency analysis)

In [32]:
df["Avatar"].value_counts().head(5)

Avatar
Teal              7
Cyan              7
CadetBlue         7
GreenYellow       7
SlateBlue         7
                 ..
PaleGoldenRod     1
Coral             1
NavajoWhite       1
PaleGreen         1
LightSlateGray    1
Name: count, Length: 138, dtype: int64

Equivalent (but more verbose):

In [35]:
df.groupby("Avatar").size().head(5)

Avatar
AliceBlue       2
AntiqueWhite    5
Aqua            6
Aquamarine      3
Azure           1
dtype: int64

# Step 6 — Sorting group results

In [36]:
df.groupby("Avatar")["Yearly Amount Spent"].mean().sort_values(ascending = False)

Avatar
DarkGray         633.135000
Coral            616.660000
LightCoral       601.820000
DarkSlateGray    593.040000
Ivory            581.235000
                    ...
Red              425.750000
Purple           420.450000
DarkBlue         419.633333
LightPink        406.722500
Navy             386.648000
Name: Yearly Amount Spent, Length: 138, dtype: float64

new commit test