In [2]:
import pandas as pd

In [9]:
df = pd.read_csv('data.csv')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   	Email                500 non-null    object
 1   Address               500 non-null    object
 2   Avatar                500 non-null    object
 3   Time on App           500 non-null    float64
 4   Time on Website       500 non-null    float64
 5   Length of Membership  500 non-null    float64
 6   Yearly Amount Spent   500 non-null    float64
dtypes: float64(4), object(3)
memory usage: 27.5+ KB

# Step 1 Build a stand alone boolean filter

In [11]:
df["Avatar"] == "Blue"

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Name: Avatar, Length: 500, dtype: bool

# Step 3: Build filter #2 as a standalone boolean checklist

In [13]:
df["Yearly Amount Spent"] > df["Yearly Amount Spent"].mean()

0       True
1      False
2      False
3       True
4       True
       ...
495     True
496     True
497     True
498    False
499    False
Name: Yearly Amount Spent, Length: 500, dtype: bool

# Step 4: Combine the checklists (and don’t screw it up)

In [19]:
(df["Avatar"] == "Blue") & (df["Yearly Amount Spent"] > df["Yearly Amount Spent"].mean())

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 500, dtype: bool

# Step 5: Apply the combined checklist inside df[ ... ]

In [20]:
df[
(df["Avatar"] == "Blue") & (df["Yearly Amount Spent"] > df["Yearly Amount Spent"].mean())
]

,\tEmail,Address,Avatar,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
266,christophermorrison@mcguire-carter.biz,"90089 Eric WellNicoleside, MT 95918",Blue,11.78,37.98,3.78,554.00
445,aschmidt@johnson.biz,Unit 1743 Box 8085DPO AE 47693-8164,Blue,11.73,35.63,4.33,513.15

In [23]:
df [
(df["Avatar"] == "Blue") & (df["Yearly Amount Spent"] > df["Yearly Amount Spent"].mean())][["\tEmail", "Yearly Amount Spent"]]

                                    \tEmail  Yearly Amount Spent
266  christophermorrison@mcguire-carter.biz               554.00
445                    aschmidt@johnson.biz               513.15

In [ ]:
df [
(df["Avatar"] == "Blue") & (df["Yearly Amount Spent"] > df["Yearly Amount Spent"].mean())][["\tEmail", "Yearly Amount Spent"]].sor