In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('data.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   	Email                500 non-null    object
 1   Address               500 non-null    object
 2   Avatar                500 non-null    object
 3   Time on App           500 non-null    float64
 4   Time on Website       500 non-null    float64
 5   Length of Membership  500 non-null    float64
 6   Yearly Amount Spent   500 non-null    float64
dtypes: float64(4), object(3)
memory usage: 27.5+ KB

# Step 1 Build a stand alone boolean filter

In [5]:
df["Avatar"] == "Blue"

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Name: Avatar, Length: 500, dtype: bool

# Step 3: Build filter #2 as a standalone boolean checklist

In [6]:
df["Yearly Amount Spent"] > df["Yearly Amount Spent"].mean()

0       True
1      False
2      False
3       True
4       True
       ...
495     True
496     True
497     True
498    False
499    False
Name: Yearly Amount Spent, Length: 500, dtype: bool

# Step 4: Combine the checklists (and don’t screw it up)

In [7]:
(df["Avatar"] == "Blue") & (df["Yearly Amount Spent"] > df["Yearly Amount Spent"].mean())

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 500, dtype: bool

# Step 5: Apply the combined checklist inside df[ ... ]

In [8]:
df[
(df["Avatar"] == "Blue") & (df["Yearly Amount Spent"] > df["Yearly Amount Spent"].mean())
]

,\tEmail,Address,Avatar,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
266,christophermorrison@mcguire-carter.biz,"90089 Eric WellNicoleside, MT 95918",Blue,11.78,37.98,3.78,554.00
445,aschmidt@johnson.biz,Unit 1743 Box 8085DPO AE 47693-8164,Blue,11.73,35.63,4.33,513.15

In [9]:
df [
(df["Avatar"] == "Blue") & (df["Yearly Amount Spent"] > df["Yearly Amount Spent"].mean())][["\tEmail", "Yearly Amount Spent"]]

                                    \tEmail  Yearly Amount Spent
266  christophermorrison@mcguire-carter.biz               554.00
445                    aschmidt@johnson.biz               513.15

In [21]:
df [
(df["Avatar"] == "Blue") & (df["Yearly Amount Spent"] > df["Yearly Amount Spent"].mean())][["\tEmail", "Yearly Amount Spent"]].sort_values(by="Yearly Amount Spent", ascending=False)

                                    \tEmail  Yearly Amount Spent
266  christophermorrison@mcguire-carter.biz               554.00
445                    aschmidt@johnson.biz               513.15

In [19]:
df.loc[:,["\tEmail", "Yearly Amount Spent"]]

                           \tEmail  Yearly Amount Spent
0        mstephenson@fernandez.com               587.95
1                hduke@hotmail.com               392.20
2                 pallen@yahoo.com               487.55
3          riverarebecca@gmail.com               581.85
4    mstephens@davidson-herman.com               599.41
..                             ...                  ...
495   lewisjessica@craig-evans.com               573.85
496            katrina56@gmail.com               529.05
497             dale88@hotmail.com               551.62
498            cwilson@hotmail.com               456.47
499      hannahwilson@davidson.com               497.78

[500 rows x 2 columns]

In [25]:
df.columns = df.columns.str.strip()

In [26]:
df.columns

Index(['Email', 'Address', 'Avatar', 'Time on App', 'Time on Website',
       'Length of Membership', 'Yearly Amount Spent'],
      dtype='object')

In [29]:
df.loc[df["Avatar"] == "Blue", ["Email", "Avatar"]]

                                      Email Avatar
266  christophermorrison@mcguire-carter.biz   Blue
289         jamesfaulkner@hoffman-wolfe.org   Blue
423                      dana59@hotmail.com   Blue
445                    aschmidt@johnson.biz   Blue

In [33]:
df.iloc[:5, 2:]

,Avatar,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
0,Violet,12.66,39.58,4.08,587.95
1,DarkGreen,11.11,37.27,2.66,392.20
2,Bisque,11.33,37.11,4.10,487.55
3,SaddleBrown,13.72,36.72,3.12,581.85
4,MediumAquaMarine,12.80,37.54,4.45,599.41

In [35]:
df.isna().sum()

Email                   0
Address                 0
Avatar                  0
Time on App             0
Time on Website         0
Length of Membership    0
Yearly Amount Spent     0
dtype: int64

In [36]:
df["Avatar"] = df["Avatar"].fillna("Unknown")