In [1]:
import pandas as pd

df = pd.read_csv("data.csv")

In [4]:
df.head(10)

,\tEmail,Address,Avatar,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
0,mstephenson@fernandez.com,"835 Frank TunnelWrightmouth, MI 82180-9605",Violet,12.66,39.58,4.08,587.95
1,hduke@hotmail.com,"4547 Archer CommonDiazchester, CA 06566-8576",DarkGreen,11.11,37.27,2.66,392.20
2,pallen@yahoo.com,"24645 Valerie Unions Suite 582Cobbborough, DC ...",Bisque,11.33,37.11,4.10,487.55
3,riverarebecca@gmail.com,"1414 David ThroughwayPort Jason, OH 22070-1220",SaddleBrown,13.72,36.72,3.12,581.85
4,mstephens@davidson-herman.com,"14023 Rodriguez PassagePort Jacobville, PR 372...",MediumAquaMarine,12.80,37.54,4.45,599.41
5,alvareznancy@lucas.biz,"645 Martha Park Apt. 611Jeffreychester, MN 672...",FloralWhite,12.03,34.48,5.49,637.10
6,katherine20@yahoo.com,"68388 Reyes Lights Suite 692Josephbury, WV 922...",DarkSlateBlue,11.37,36.68,4.69,521.57
7,awatkins@yahoo.com,Unit 6538 Box 8980DPO AP 09026-4941,Aqua,12.35,37.37,4.43,549.90
8,vchurch@walter-martinez.com,"860 Lee KeyWest Debra, SD 97450-0495",Salmon,13.39,37.53,3.27,570.20
9,bonnie69@lin.biz,"PSC 2734, Box 5255APO AA 98456-7482",Brown,11.81,37.15,3.20,427.20

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   	Email                500 non-null    object
 1   Address               500 non-null    object
 2   Avatar                500 non-null    object
 3   Time on App           500 non-null    float64
 4   Time on Website       500 non-null    float64
 5   Length of Membership  500 non-null    float64
 6   Yearly Amount Spent   500 non-null    float64
dtypes: float64(4), object(3)
memory usage: 27.5+ KB

In [6]:
df.describe()

       Time on App  Time on Website  Length of Membership  Yearly Amount Spent
count   500.000000       500.000000             500.00000           500.000000
mean     12.052620        37.060480               3.53336           499.314240
std       0.994418         1.010555               0.99926            79.314764
min       8.510000        33.910000               0.27000           256.670000
25%      11.390000        36.347500               2.93000           445.037500
50%      11.980000        37.070000               3.53500           498.890000
75%      12.752500        37.720000               4.13000           549.312500
max      15.130000        40.010000               6.92000           765.520000

In [7]:
df["Yearly Amount Spent"]

0      587.95
1      392.20
2      487.55
3      581.85
4      599.41
        ...
495    573.85
496    529.05
497    551.62
498    456.47
499    497.78
Name: Yearly Amount Spent, Length: 500, dtype: float64

In [8]:
type(df["Yearly Amount Spent"])

pandas.core.series.Series

In [9]:
df[df["Yearly Amount Spent"] > df["Yearly Amount Spent"].mean()]

,\tEmail,Address,Avatar,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
0,mstephenson@fernandez.com,"835 Frank TunnelWrightmouth, MI 82180-9605",Violet,12.66,39.58,4.08,587.95
3,riverarebecca@gmail.com,"1414 David ThroughwayPort Jason, OH 22070-1220",SaddleBrown,13.72,36.72,3.12,581.85
4,mstephens@davidson-herman.com,"14023 Rodriguez PassagePort Jacobville, PR 372...",MediumAquaMarine,12.80,37.54,4.45,599.41
5,alvareznancy@lucas.biz,"645 Martha Park Apt. 611Jeffreychester, MN 672...",FloralWhite,12.03,34.48,5.49,637.10
6,katherine20@yahoo.com,"68388 Reyes Lights Suite 692Josephbury, WV 922...",DarkSlateBlue,11.37,36.68,4.69,521.57
...,...,...,...,...,...,...,...
493,nathan84@lowery.net,"01242 Stephanie Ways Suite 003Churchville, MO ...",MediumSeaGreen,12.63,35.54,5.41,627.60
494,kellydeborah@chan.biz,"354 Sanchez Wall Suite 884Juliabury, VI 39735",DarkTurquoise,13.35,37.97,2.77,510.66
495,lewisjessica@craig-evans.com,"4483 Jones Motorway Suite 872Lake Jamiefurt, U...",Tan,13.57,36.42,3.75,573.85
496,katrina56@gmail.com,"172 Owen Divide Suite 497West Richard, CA 19320",PaleVioletRed,11.70,37.19,3.58,529.05
497,dale88@hotmail.com,"0787 Andrews Ranch Apt. 633South Chadburgh, TN...",Cornsilk,11.50,38.33,4.96,551.62

In [10]:
df ["Avatar"].unique()

array(['Violet', 'DarkGreen', 'Bisque', 'SaddleBrown', 'MediumAquaMarine',
       'FloralWhite', 'DarkSlateBlue', 'Aqua', 'Salmon', 'Brown',
       'Tomato', 'RoyalBlue', 'DarkBlue', 'Peru', 'PowderBlue',
       'OliveDrab', 'Cyan', 'LightSeaGreen', 'PeachPuff', 'Black',
       'Olive', 'Silver', 'Wheat', 'Teal', 'Linen', 'MediumSlateBlue',
       'LemonChiffon', 'DarkOrchid', 'SeaGreen', 'SteelBlue',
       'DarkMagenta', 'DarkGoldenRod', 'DarkSeaGreen', 'Gainsboro',
       'HotPink', 'HoneyDew', 'WhiteSmoke', 'GhostWhite', 'Chocolate',
       'Snow', 'BurlyWood', 'Moccasin', 'BlueViolet', 'MediumBlue',
       'GreenYellow', 'SandyBrown', 'MediumVioletRed', 'DarkOliveGreen',
       'DarkSalmon', 'DeepPink', 'SkyBlue', 'Magenta', 'DarkTurquoise',
       'SpringGreen', 'OrangeRed', 'LimeGreen', 'LightGreen',
       'LightYellow', 'MintCream', 'DimGray', 'Indigo', 'LightSalmon',
       'DeepSkyBlue', 'Turquoise', 'LightSteelBlue', 'Cornsilk',
       'DarkKhaki', 'FireBrick', 'SlateGray', 'Crimson', 'MidnightBlue',
       'DarkCyan', 'OldLace', 'Gray', 'LightPink', 'BlanchedAlmond',
       'CadetBlue', 'PaleTurquoise', 'Chartreuse', 'Khaki',
       'MediumSpringGreen', 'Lime', 'SlateBlue', 'Orange', 'Fuchsia',
       'GoldenRod', 'ForestGreen', 'Green', 'LightSkyBlue', 'Azure',
       'LightGray', 'MediumOrchid', 'Sienna', 'Aquamarine', 'Purple',
       'CornflowerBlue', 'DarkSlateGray', 'DarkRed', 'DarkViolet',
       'LavenderBlush', 'Navy', 'RosyBrown', 'Pink', 'Red', 'Lavender',
       'White', 'MediumSeaGreen', 'MediumPurple', 'Tan', 'LawnGreen',
       'Thistle', 'Orchid', 'Yellow', 'AntiqueWhite', 'AliceBlue',
       'PapayaWhip', 'Gold', 'MediumTurquoise', 'YellowGreen',
       'LightCyan', 'LightCoral', 'SeaShell', 'LightGoldenRodYellow',
       'Blue', 'LightBlue', 'PaleGoldenRod', 'Coral', 'DarkOrange',
       'Ivory', 'PaleVioletRed', 'DarkGray', 'MistyRose', 'NavajoWhite',
       'DodgerBlue', 'IndianRed', 'PaleGreen', 'LightSlateGray', 'Beige'],
      dtype=object)

In [12]:
df[df["Avatar"]== "Blue"]

,\tEmail,Address,Avatar,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
266,christophermorrison@mcguire-carter.biz,"90089 Eric WellNicoleside, MT 95918",Blue,11.78,37.98,3.78,554.00
289,jamesfaulkner@hoffman-wolfe.org,Unit 0474 Box 0661DPO AP 48938-3469,Blue,12.81,38.55,1.81,467.43
423,dana59@hotmail.com,"31927 Jill MountainSouth Jessica, MN 63418",Blue,10.40,36.68,3.86,461.11
445,aschmidt@johnson.biz,Unit 1743 Box 8085DPO AE 47693-8164,Blue,11.73,35.63,4.33,513.15

In [19]:
df[(df["Yearly Amount Spent"] > df["Yearly Amount Spent"].mean()) & (df["Avatar"] == "Blue")]

,\tEmail,Address,Avatar,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
266,christophermorrison@mcguire-carter.biz,"90089 Eric WellNicoleside, MT 95918",Blue,11.78,37.98,3.78,554.00
445,aschmidt@johnson.biz,Unit 1743 Box 8085DPO AE 47693-8164,Blue,11.73,35.63,4.33,513.15

In [20]:
df.columns

Index(['\tEmail', 'Address', 'Avatar', 'Time on App', 'Time on Website',
       'Length of Membership', 'Yearly Amount Spent'],
      dtype='object')

In [22]:
df.columns = df.columns.str.strip()

In [23]:
df.columns

Index(['Email', 'Address', 'Avatar', 'Time on App', 'Time on Website',
       'Length of Membership', 'Yearly Amount Spent'],
      dtype='object')

In [34]:
df[["Email", "Yearly Amount Spent"]]

                             Email  Yearly Amount Spent
0        mstephenson@fernandez.com               587.95
1                hduke@hotmail.com               392.20
2                 pallen@yahoo.com               487.55
3          riverarebecca@gmail.com               581.85
4    mstephens@davidson-herman.com               599.41
..                             ...                  ...
495   lewisjessica@craig-evans.com               573.85
496            katrina56@gmail.com               529.05
497             dale88@hotmail.com               551.62
498            cwilson@hotmail.com               456.47
499      hannahwilson@davidson.com               497.78

[500 rows x 2 columns]

In [38]:
df[
(df["Avatar"] == "Blue") &
(df["Yearly Amount Spent"] > df["Yearly Amount Spent"].median())
]

,Email,Address,Avatar,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
266,christophermorrison@mcguire-carter.biz,"90089 Eric WellNicoleside, MT 95918",Blue,11.78,37.98,3.78,554.00
445,aschmidt@johnson.biz,Unit 1743 Box 8085DPO AE 47693-8164,Blue,11.73,35.63,4.33,513.15

In [42]:
df[["Email", "Yearly Amount Spent"]].sort_values(by="Yearly Amount Spent", ascending=False)

                               Email  Yearly Amount Spent
65                    kyang@diaz.org               765.52
157                 asilva@yahoo.com               744.22
50               william82@gmail.com               725.58
205  jeffrey54@mcdonald-williams.com               712.40
368               rhonda01@gmail.com               708.94
..                               ...                  ...
173          fischermonica@gmail.com               298.76
299         morganorozco@hotmail.com               282.47
415                brian51@cook.info               275.92
303         brandon77@richardson.com               266.09
225    alexandra26@summers-davis.com               256.67

[500 rows x 2 columns]